### ISSUE TITLE
Does this library use Firebase (Google) services?

### ISSUE THREAD

**Issue by tabekg** [mohesu/barcode_scanner#68]
I am developing a service for China. Will not be there any problems with using this library on my application?

**Comment by FrankenApps** [comment]
I don't think this was sufficiently answered yet.
I checked the code and MLKit is used, so this actually is a concern for example in europe.

Basically the problem is described in more detail here https://github.com/juliansteenbakker/mobile_scanner/issues/706 or here https://github.com/juliansteenbakker/mobile_scanner/issues/553
